### ISSUE TITLE
Error with current version 2.0.4

### ISSUE THREAD

**Issue by Dreamfish19** [Tusko/brackets-wp-hint#10]
![error_brackets](https://cloud.githubusercontent.com/assets/9974678/8061974/9ff40878-0ecd-11e5-9bd5-9a71c16d1943.PNG)

Hi, on Brackets 1.3.0 (Windows 8.1 // German) I'm getting the following error in the console:

[Extension] failed to load C:/Users/Alexander/AppData/Roaming/Brackets/extensions/user/brackets-wp-functions-hint - Error: Load timeout for modules: text!wp-func.txt_unnormalized2,text!wp-func.txt
http://requirejs.org/docs/errors.html#timeout

I already reinstalled the module without luck ..

**Comment by Tusko** [comment]
Hi @Dreamfish19.
I don't have this problems in early versions

**Comment by Dreamfish19** [comment]
Hi,
I've installed:

PHP SmartHints
Brackets SASS
Brackets Snippets
Brackets Wordpress Hint
Emmet
IndentGuides
Minifier
Projects
SASSHints

Ciao,
Alex
