### ISSUE TITLE
Newline extreme slowdown (OS X, Yosemite)

### ISSUE THREAD

**Issue by manomoreno** [Tusko/brackets-wp-hint#16]
## Description

**Hello,** maybe it is related to #13.

Some heavy load routine is being executed on each new line when pressing ENTER, making it queue these executions, extremely slowing down newlines added. Could someone else confirm this issue?
## **System**
- OS X Yosemite, Version 10.10.5 (14F1605);
- MacBook Pro (Retina, 15-inch, Mid 2014).
## **Error reproduction**

[bug_newlineSlowdown.zip](https://github.com/Tusko/brackets-wp-hint/files/121579/bug_newlineSlowdown.zip) (video)

**Comment by slawekniewiadomski** [comment]
Same on My w7, actual stable Brackets, after disabling plugin, newline behaves as it should, after enabling really laggy newlines.

**Comment by oupsouch** [comment]
Same issue here on latest Brackets on Windows 10. I tried to disable all other extensions but no luck. 
It seem like this issue has been existed a long time but not got fixed by author :(
What a pity! This is a awesome extension for Wordpress development but don't have chance to use this.

**Comment by manomoreno** [comment]
I'll probably have some time on the next weeks. Although I don't have any environment ready for brackets, I'll take at least an overall look at the possible areas the bug is coming from.

**Comment by dylandestpern** [comment]
Any updates on this issue?

**Comment by Tusko** [comment]
@dylandestpern 
still haven't time to do that, sorry.

**Comment by Tusko** [comment]
Fixed https://github.com/Tusko/brackets-wp-hint/commit/1320d25f71dbc86fa8ef952a978ede1e71ae44d3
