### ISSUE TITLE
Invalid function

### ISSUE THREAD

**Issue by wolffe** [Tusko/brackets-wp-hint#25]
While working on sanitizing a bunch of variables, I constantly get an invalid function before the valid one:

    sanitize_text_fields()
    sanitize_text_field()

There is no **public** `sanitize_text_fields()` function in WordPress.

This function gets suggested first, and I press Enter by habit and when I refresh the browser, I get errors everywhere:

`Fatal error: Uncaught Error: Call to undefined function sanitize_text_fields()`

**UPDATE:** This function’s access is marked private. This means it is not intended for use by plugin or theme developers, only in other core functions. It is listed here for completeness.

https://developer.wordpress.org/reference/functions/_sanitize_text_fields/

**Comment by wolffe** [comment]
Now I wonder if the functions should be separated by public and core only in a small options panel.

**Comment by Tusko** [comment]
@wolffe please create pull request
