### ISSUE TITLE
V4.0.1 really slows down newline in editor

### ISSUE THREAD

**Issue by brianshim** [Tusko/brackets-wp-hint#31]
First of all, thank you for your work on this extension.

An old problem seems to have come up again in V4.0.1. When you press return there is up to a 3-second lag until the cursor actually moves.  I disabled this extension and the editor is snappy again. Replicated both on Windows 10 and Mac OS High Sierra, although it's worse on Windows.

**Comment by Tusko** [comment]
@brianshim 
I don't have any delays while input.
Check out my demo http://cl.ly/005e8b

**Comment by brianshim** [comment]
Yes, it's fixed now.  Many thanks.

**Comment by Tusko** [comment]
It may be slow at a first input when it loads more than 7k strings of functions, classes, etc.
