### ISSUE TITLE
Brackets got stuck when typing any php code

### ISSUE THREAD

**Issue by onlypds2xhtml** [Tusko/brackets-wp-hint#32]
hi there, 
how are you  ?

Brackets got stuck when typing any php code 
can tell me how can we solve this issue, 

waiting for your reply

Regards,
Rahul

**Comment by Tusko** [comment]
Hey, @onlypds2xhtml .
I don't understand what you meant.
Can you provide some screenshot/video?

**Comment by Tusko** [comment]
@onlypds2xhtml 
Check out my demo http://cl.ly/005e8b
