### ISSUE TITLE
freeze ?> #reopen

### ISSUE THREAD

**Issue by Htmlbelov** [Tusko/brackets-wp-hint#36]
Ya know.
It is loading more than 7k lines in memory while first input

_Originally posted by @Tusko in https://github.com/Tusko/brackets-wp-hint/issues/35#issuecomment-568466285_

So, is there any solution to this problem? A really useful extension, but these 'freeze' make it impossible to use it normally(

**Comment by Tusko** [comment]
Please try to update to `v.4.0.3` it may to fix freeze on start typing.

**Comment by Htmlbelov** [comment]
nope, still freeze

**Comment by Tusko** [comment]
Can you make the video?

**Comment by Htmlbelov** [comment]
https://youtu.be/Ke3yMsZKXEc

I type quickly, a pause is visible on the video before the question mark appears

**Comment by Tusko** [comment]
![2D0FE621-8667-4D9A-A72B-B0372228AE69](https://user-images.githubusercontent.com/2039259/72210997-34153800-34cc-11ea-8fea-86a29f6f6d7c.jpeg)

**Comment by Htmlbelov** [comment]
shit happens)

**Comment by Htmlbelov** [comment]
and no options?

**Comment by Tusko** [comment]
I have no idea

**Comment by brianshim** [comment]
Happening for me too in V34.0.3 after update, if I  understand the issue correctly. There's a 1 second delay from when I start typing on a line until when the character appears. No delay after you start typing though. Didn't happen in the version I had before (sorry I don't know what version that was). Disabling extension makes problem go away.
