### ISSUE TITLE
I need more help on how to install this extension

### ISSUE THREAD

**Issue by Daniel-Marcus8** [Tusko/brackets-wp-hint#37]
I've never installed an extension to Brackets.  I've downloaded the zip file into my download directory on my Windows computer.  I see the Show Brackets Extension menu item under Help in Brackets.  I don't understand where to put files from the zip file onto my machine.  I also don't understand where I should be running the npm commands you have in the readme file.  Sorry for being dense, but can you please send the all the steps for integrating this into my Brackets setup.   Thank you.

**Comment by Tusko** [comment]
https://youtu.be/it8mxwavToU
