### ISSUE TITLE
issue with phpmailer_init

### ISSUE THREAD

**Issue by kavillock** [Tusko/brackets-wp-hint#6]
if i want open php tag, "<?php", i got hint "phpmailer_init", so, when i want type "<?php" and go to new line, i type "<?phpmailer_init"

**Comment by Tusko** [comment]
https://github.com/Tusko/brackets-wp-hint/commit/d7d659f124be2536e3150b14eae40d8f1bf3eda7

**Comment by misfist** [comment]
Thanks, this was super annoying. 
I removed phpmailer_init from the file wp-func.txt and it's no longer a problem.
