### ISSUE TITLE
Latest version fails to install

### ISSUE THREAD

**Issue by onetrev** [Tusko/brackets-wp-hint#8]
I'm running Brackets 1.3 and tried updating to WP Hints v2.0.1 and receive an error when the extension tries to start up.

In the Brackets console it shows as this: 

"[Extension] failed to load C:/Users/Trevor/AppData/Roaming/Brackets/extensions/user/brackets-wp-functions-hint - ReferenceError: lastLine is not defined"

Please let me know if you need more details! Thanks.

**Comment by nickfmc** [comment]
I too get this error

![screen](https://cloud.githubusercontent.com/assets/8106386/7417633/368f13e4-ef1c-11e4-8ee4-fa4bed7c047c.PNG)

**Comment by oleg-ds11** [comment]
I have the same problem. I just tried to install Brackets WP Hint in the first time. Brackets version 1.3.

**Comment by Tusko** [comment]
fixed in https://github.com/Tusko/brackets-wp-hint/commit/f19750fcc66949abf4d6251b4f44dd42f71e33e4
